In [1]:
import numpy as np

In [2]:
%store -r asset_11

In [3]:
asset_11

,IVV,EFA,EEM,VIG,SHY,LQD,EMB,MUB,TIP,VNQ,XLE
Date,,,,,,,,,,,
2009-06-01,34.372078,27.405502,32.856422,75.464882,65.979172,57.978580,75.367775,79.873070,22.627659,41.031338,93.709999
2009-06-08,35.200672,27.511499,32.952915,75.637337,67.205452,57.947876,74.506866,80.430000,22.154604,42.133686,92.169998
2009-06-15,34.110424,25.888861,32.100529,75.773560,66.913620,57.216545,74.664856,80.381813,20.663181,38.747875,91.900002
2009-06-22,33.405388,26.353636,31.875370,76.046059,68.155602,57.345604,75.026123,80.959618,20.268965,37.901199,92.290001
2009-06-29,33.573315,26.239273,31.507488,76.091499,67.673752,57.609863,74.807808,80.879372,19.953926,36.532040,91.250000
2009-07-06,32.682583,25.417244,30.989782,76.366264,68.786652,57.598324,75.816391,81.077332,19.079107,35.352818,89.580002
2009-07-13,34.753544,27.595634,32.809872,76.175285,68.220795,58.209839,75.997543,80.932358,20.461460,38.344402,91.930000
2009-07-20,36.564709,29.099951,33.869541,76.129799,69.359299,59.167221,76.020203,81.012856,22.144321,40.512901,93.410004
2009-07-27,37.418331,29.412323,34.168839,76.120644,71.213631,59.618137,76.337181,81.633156,22.939003,40.061790,93.349998
2009-08-03,37.796894,30.028845,34.815987,75.693176,69.672890,60.489033,76.344742,80.618187,26.792225,40.227985,93.750000
2009-08-10,38.027000,29.363007,34.516678,76.204468,70.632774,60.648277,76.732399,81.333015,25.563469,40.133018,93.000000
2009-08-17,38.858349,29.848005,35.244709,76.168037,70.810837,60.803383,77.088226,82.376587,25.877335,41.430946,93.650002
2009-08-24,39.392792,29.609617,35.188091,76.377533,71.797264,60.939926,77.716644,82.392761,26.645311,41.296402,93.870003
2009-08-31,38.969700,29.921991,34.945412,76.368385,71.831436,60.871681,78.269356,81.907394,25.096003,40.330868,97.529999
2009-09-07,40.535908,31.122149,35.673439,76.503304,73.092026,62.214127,79.046959,83.471016,26.825609,42.420227,98.779999
2009-09-14,41.270763,32.083927,36.514717,76.430321,72.803070,63.873169,79.593735,83.217911,29.116171,43.670670,98.669998
2009-09-21,40.268681,31.311224,35.584454,76.548897,73.580704,63.629929,79.965843,83.544464,27.279715,42.576885,97.000000
2009-09-28,39.088451,31.122149,35.354904,76.621841,71.873985,63.760883,79.449471,84.017921,26.510309,41.312927,98.370003
2009-10-05,40.951569,32.757996,36.859196,76.589012,71.847809,65.152000,78.639481,83.950172,27.899567,44.643719,102.839996
2009-10-12,41.649326,33.497822,37.412128,76.625504,71.930740,64.957764,78.403366,84.595383,27.488180,46.893391,103.180000
2009-10-19,41.693867,33.506046,37.135651,76.506821,72.483719,64.675865,78.654701,84.276871,27.596087,46.344883,103.489998
2009-10-26,39.563522,30.883762,35.940346,76.716866,73.050568,63.911587,78.251060,84.946556,26.705896,43.920319,102.529999
2009-11-02,40.832809,32.593590,37.062489,76.662025,72.801727,63.535686,77.839729,85.199760,26.665426,45.375061,107.430000
2009-11-09,41.849739,33.736217,37.794285,76.908989,73.615837,64.514397,78.091370,85.718437,28.378382,45.526089,109.739998
2009-11-16,41.077778,33.415627,37.843075,77.018822,73.574181,64.596161,78.335823,86.578842,28.209782,44.993492,112.940002
2009-11-23,40.981277,32.988167,37.859348,77.165245,74.108879,64.533241,78.649048,87.275337,27.434229,45.327366,115.059998
2009-11-30,42.065006,34.393841,38.249638,76.359879,73.476921,64.149437,78.786575,85.923317,29.875530,44.437035,113.750000
2009-12-07,41.166847,33.991047,38.306568,76.963371,73.358276,64.370697,79.017586,85.565910,29.369736,44.142902,109.320000
2009-12-14,40.706631,33.177231,37.989445,77.009499,73.706978,64.459160,79.002205,86.239082,29.835062,44.635761,108.949997
2009-12-21,41.248493,33.867744,38.428516,76.705338,72.932899,64.389687,78.948586,85.204666,30.968044,46.205490,108.360001
...,...,...,...,...,...,...,...,...,...,...,...
2018-11-05,61.410713,38.914261,106.245522,81.556694,109.178276,100.017464,104.894989,106.838188,78.329544,66.727982,114.480003
2018-11-12,60.974899,39.989780,105.811859,81.783005,108.740318,99.462936,105.346382,107.516815,78.514198,65.442123,115.620003
2018-11-19,59.832104,38.855598,102.421463,81.812500,108.652718,98.411232,105.562241,107.093910,77.727013,62.256721,115.769997
2018-11-26,60.790894,40.165779,106.393349,81.910904,108.477539,99.137863,106.013626,107.467636,79.670677,64.399811,115.540001
2018-12-03,58.834579,38.992485,101.583717,81.930573,108.896034,99.501190,106.572922,108.008568,79.806732,62.412579,118.089996
2018-12-10,58.553726,38.943600,100.322182,82.109985,110.062141,100.495735,106.565277,107.403618,77.406303,60.483799,117.059998
2018-12-17,55.745163,37.662750,93.393555,82.188828,109.671600,98.863213,106.889786,107.521820,73.158318,54.658501,118.720001
2018-12-24,57.450626,38.943077,96.116524,82.503685,110.191048,100.678802,107.343590,107.959732,73.138649,56.094021,121.059998
2018-12-31,58.644863,39.389668,96.988777,82.533302,110.817841,102.224709,107.432281,108.610863,73.089478,58.866768,121.440002
2019-01-07,59.741211,40.421799,99.377571,82.523438,111.405487,102.594177,107.333740,108.788437,76.462685,60.970909,121.800003
2019-01-14,60.769043,41.235592,102.192566,82.454346,111.816826,103.760895,107.373154,108.265572,78.114876,62.770241,121.019997
2019-01-21,60.857136,41.880676,102.033981,82.513573,112.678696,104.713707,107.383011,108.206367,79.127823,61.875492,122.860001
2019-01-28,61.336792,42.436436,103.005356,82.493828,113.599312,105.579041,107.481537,109.192932,81.507744,63.802647,124.500000
2019-02-04,60.710308,41.840977,104.016373,82.772209,114.297859,105.140526,108.126549,109.271858,82.727219,61.885323,124.209999
2019-02-11,62.276520,41.771507,107.475662,82.742546,114.170158,105.657944,108.245056,109.350784,83.681152,65.012047,124.800003
2019-02-18,62.765965,42.714321,108.090210,82.821655,114.327332,106.185097,108.472168,109.745407,83.710670,64.658073,125.500000
2019-02-25,63.255405,42.168484,108.298355,82.604118,113.433388,105.472458,108.205559,109.173210,82.343681,65.336502,121.879997
2019-03-04,62.129688,41.324913,105.750969,82.944519,114.710732,105.854370,108.914642,109.824326,82.471527,62.829239,122.839996
2019-03-11,63.842731,42.754017,108.040634,83.013847,115.154167,106.883614,109.033409,110.495201,84.340073,64.412262,122.970001
2019-03-18,62.951946,42.108936,107.128746,83.241692,116.819504,107.265900,109.854851,111.442299,84.792450,64.877808,123.970001
2019-03-25,63.490334,42.595226,108.675003,83.330849,117.322052,107.883438,110.042892,111.550827,85.471031,65.521935,122.010002
2019-04-01,64.850983,44.064030,110.361801,83.093094,116.819504,107.844223,109.597519,111.106873,87.003281,66.998451,121.980003
2019-04-08,65.036972,44.024330,111.317833,83.215706,117.636360,107.739731,109.760231,111.047676,87.211288,66.948898,121.830002
2019-04-15,65.262108,44.222820,111.815765,83.265343,117.201469,107.788948,109.958588,111.146339,84.675667,66.582253,120.370003
2019-04-22,65.046753,43.547966,112.512878,83.453926,118.249146,107.808640,110.573486,111.925705,85.973190,65.621025,121.370003
2019-04-29,65.575356,43.885391,112.951050,83.245491,117.547394,108.044853,110.543732,111.373238,86.834900,63.668842,120.650002
2019-05-06,63.950409,41.662338,111.517014,83.549324,117.826096,108.053627,111.204491,111.782654,86.032616,63.470654,121.430000
2019-05-13,63.402229,39.985130,110.919487,83.678604,118.212700,107.687950,111.741180,112.039246,87.023094,63.173367,120.650002
2019-05-20,63.412022,39.647701,110.292091,83.758156,118.688538,108.201881,111.810753,112.414261,87.221184,61.062630,121.300003
2019-05-27,62.061165,40.401951,108.001602,84.086311,119.778969,108.607094,112.178490,113.756393,86.062332,58.238411,123.330002

In [4]:
testing_period = '2015-06-01'

In [5]:
df = asset_11.loc[(asset_11.index > testing_period)]

In [6]:
df.head(2)

,IVV,EFA,EEM,VIG,SHY,LQD,EMB,MUB,TIP,VNQ,XLE
Date,,,,,,,,,,,
2015-06-08,57.871342,36.748619,73.769173,80.486794,100.606331,89.097290,97.976440,103.189217,64.342896,67.761108,113.230003
2015-06-15,57.740211,36.584236,74.400932,80.648430,101.188171,89.715935,98.302788,104.244545,65.447838,66.819145,115.120003

In [7]:
df.tail(2)

,IVV,EFA,EEM,VIG,SHY,LQD,EMB,MUB,TIP,VNQ,XLE
Date,,,,,,,,,,,
2019-05-20,63.412022,39.647701,110.292091,83.758156,118.688538,108.201881,111.810753,112.414261,87.221184,61.062630,121.300003
2019-05-27,62.061165,40.401951,108.001602,84.086311,119.778969,108.607094,112.178490,113.756393,86.062332,58.238411,123.330002

## CAPM

In [8]:
df.std()

IVV     6.007261
EFA     5.628240
EEM    13.090012
VIG     0.668841
SHY     4.634449
LQD     6.030886
EMB     2.833355
MUB     2.420724
TIP     5.658617
VNQ     5.519462
XLE     6.641942
dtype: float32

In [9]:
cov_matrix = asset_11.pct_change().cov()

In [10]:
#from the calculations in the CAPM Excel
weights = [0.3690, 0.1167,0.0500, 0.0943, 0.0360, 
          0.0741, 0.0318, 0.0287, 0.0414, 0.1376, 0.0204]

In [11]:
np.sum(weights)

1.0

In [12]:
std = np.sqrt(np.dot(weights, np.dot(cov_matrix, weights))) * np.sqrt(52)

In [13]:
print(std)

0.12233251073306874

In [14]:
rf=0.01
exp_ret = 0.06008

In [15]:
sharpe_ratio = (exp_ret-rf)/std
print(sharpe_ratio)

0.4093760497507916

## EQWT

In [16]:
weekly_returns = df.pct_change().dropna()

In [17]:
weekly_returns.head()

,IVV,EFA,EEM,VIG,SHY,LQD,EMB,MUB,TIP,VNQ,XLE
Date,,,,,,,,,,,
2015-06-15,-0.002266,-0.004473,0.008564,0.002008,0.005783,0.006943,0.003331,0.010227,0.017173,-0.013901,0.016692
2015-06-22,-0.004693,-0.002496,-0.014398,-0.001297,-0.013560,-0.002540,-0.002951,-0.010390,-0.036558,0.008232,-0.022238
2015-06-29,-0.010333,0.002910,-0.004517,0.001889,0.004524,0.000364,0.000185,0.006192,0.012906,-0.020389,-0.007107
2015-07-06,0.005002,-0.033685,0.005802,-0.000023,-0.000701,0.003032,0.004567,-0.002765,0.021679,-0.013563,-0.002416
2015-07-13,0.015707,0.008324,0.012664,-0.000354,0.003564,-0.001820,0.002491,0.001520,0.009645,-0.013885,-0.025473

In [18]:
weights2 = [0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909]

In [19]:
exp_ret = np.sum((weekly_returns.mean()*weights2)*52)

In [20]:
exp_ret

0.03974033543835394

In [21]:
exp_std = np.sqrt(np.dot(weights2,np.dot(weekly_returns.cov()*52,weights2)))

In [22]:
print(exp_std)

0.0680580622648593

In [23]:
sharpe_ratio = (exp_ret-rf)/exp_std
print(sharpe_ratio)

0.4369847516759213